FROM debian:latest

MAINTAINER f00b4rch@gmail.com

RUN apt-get update && apt-get install python-glanceclient python-novaclient -y

env OS_AUTH_URL=""
env OS_TENANT_ID=""
env OS_TENANT_NAME=""
env OS_USERNAME=""
env OS_PASSWORD=""
env OS_REGION_NAME=""
