#!/bin/bash

sshuser = ""
destip = ""

nginx -t && \
/bin/rsync -avh /etc/nginx/ $sshuser@$destip:/etc/nginx --delete && \
ssh -t $sshuser@$destip "nginx -t && systemctl reload nginx" && \
echo -ne "\n\n[SUCCESS]\n\n"
