#F00b4rch
FROM perl
COPY . /usr/src/perl/
WORKDIR /usr/src/perl/
RUN curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -n Mojolicious &&\
    chmod +x /usr/src/perl/start.sh &&\
    chmod +x /usr/src/perl/apitools.pl  
EXPOSE  8080
CMD [ "/bin/bash", "start.sh" ]